import { Injectable, signal, computed } from '@angular/core';

export type Lang = 'en' | 'zh';

const DICTIONARY = {
  en: {
    alarms: 'Conditional Alarms',
    newAlarm: 'New Conditional Alarm',
    editAlarm: 'Edit Conditional Alarm',
    alarmLabel: 'Label',
    snooze: 'Snooze',
    snoozeDuration: 'Duration',
    sound: 'Sound',
    edit: 'Edit',
    editLoop: 'Edit Loop Timer',
    groupTimer: 'Workout Alarm',
    timer: 'Timer',
    loops: 'Loops',
    lap: 'Lap',
    reset: 'Reset',
    start: 'Start',
    stop: 'Stop',
    pause: 'Pause',
    resume: 'Resume',
    cancel: 'Cancel',
    hours: 'Hours',
    min: 'Min',
    sec: 'Sec',
    day: 'Days',
    week: 'Weeks',
    month: 'Months',
    year: 'Years',
    loopTimers: 'Loop Timers',
    newLoop: 'New Loop Timer',
    actName: 'Activity Name',
    repeatEvery: 'Repeat Every',
    unit: 'Unit',
    actHours: 'Active Hours',
    actDays: 'Active Days', 
    repeat: 'Repeat', 
    save: 'Save',
    delete: 'Delete',
    alarmRinging: 'Alarm Ringing!',
    stopAlarm: 'Stop',
    noLoops: 'No loop timers set',
    noAlarms: 'No conditional alarms set',
    noTimers: 'No timers set',
    noGroups: 'No workout alarms set',
    close: 'Close',
    off: 'Off',
    hrs: 'Hrs',
    language: 'Language',
    confirmDelete: 'Are you sure you want to delete this item?',
    confirm: 'Confirm',
    newTimer: 'New Timer',
    recent: 'Recents',
    totalDuration: 'Total Duration',
    endsAt: 'Ends At',
    never: 'Never',
    daily: 'Daily',
    weekdays: 'Weekdays',
    weekends: 'Weekends',
    timerName: 'Timer Label',
    enterTimerName: 'Timer',
    // Group Timer
    newGroup: 'New Workout',
    groupName: 'Workout Name',
    intervals: 'Intervals',
    addInterval: 'Add Interval',
    prep: 'Prep',
    work: 'Work',
    post: 'Post',
    ready: 'Ready',
    next: 'Next',
    completed: 'Completed',
    totalSets: 'Sets',
    // Tasks
    selectTasks: 'Wake Up Tasks',
    taskShake: 'Shake (20s)',
    taskMath: 'Math (5)',
    taskStroop: 'Stroop Test (7)',
    taskStep: 'Walk (40 steps)',
    taskShakeInstr: 'Shake your phone vigorously!',
    taskMathInstr: 'Solve the equation',
    taskStroopInstr: 'Tap the color of the TEXT',
    taskStepInstr: 'Walk holding your phone',
    tasksRemaining: 'tasks remaining',
    // Shake Alarm
    shakeAlarm: 'Shake Alarm',
    shakeTotalTime: 'Total Duration',
    shakePoints: 'Shake Points',
    addShakePoint: 'Add Point',
    shakeNow: 'Time to Shake!',
    shakeFinished: 'Time is Up!',
    completeShake: 'Shake Completed',
    finish: 'Finish',
    noShakeAlarms: 'No shake alarms set',
    shakePoint: 'Point',
    running: 'Running'
  },
  zh: {
    alarms: '条件闹钟',
    newAlarm: '新建条件闹钟',
    editAlarm: '编辑条件闹钟',
    alarmLabel: '标签',
    snooze: '稍后提醒',
    snoozeDuration: '时长',
    sound: '铃声',
    edit: '编辑',
    editLoop: '编辑循环任务',
    groupTimer: '运动闹钟',
    timer: '计时器',
    loops: '循环闹钟',
    lap: '计次',
    reset: '重置',
    start: '开始',
    stop: '停止',
    pause: '暂停',
    resume: '继续',
    cancel: '取消',
    hours: '小时',
    min: '分钟',
    sec: '秒',
    day: '天',
    week: '周',
    month: '月',
    year: '年',
    loopTimers: '循环任务',
    newLoop: '新建循环',
    actName: '任务名称',
    repeatEvery: '重复间隔',
    unit: '单位',
    actHours: '活跃时段',
    actDays: '活跃日期',
    repeat: '重复',
    save: '保存',
    delete: '删除',
    alarmRinging: '闹钟响了!',
    stopAlarm: '停止',
    noLoops: '暂无循环任务',
    noAlarms: '暂无条件闹钟',
    noTimers: '暂无计时器',
    noGroups: '暂无运动闹钟',
    close: '关闭',
    off: '已关闭',
    hrs: '小时',
    language: '语言',
    confirmDelete: '确定要删除此项吗？',
    confirm: '确认',
    newTimer: '新建计时',
    recent: '最近',
    totalDuration: '总时长',
    endsAt: '结束于',
    never: '从不',
    daily: '每天',
    weekdays: '工作日',
    weekends: '周末',
    timerName: '计时备注',
    enterTimerName: '计时器',
    // Group Timer
    newGroup: '新建运动闹钟',
    groupName: '运动名称',
    intervals: '阶段列表',
    addInterval: '添加阶段',
    prep: '准备',
    work: '运动',
    post: '缓冲',
    ready: '就绪',
    next: '下个阶段',
    completed: '已完成',
    totalSets: '组数',
    // Tasks
    selectTasks: '解锁任务',
    taskShake: '疯狂摇晃 (20秒)',
    taskMath: '数学题 (5道)',
    taskStroop: '色词测试 (7次)',
    taskStep: '持机行走 (40步)',
    taskShakeInstr: '持续摇晃手机！',
    taskMathInstr: '计算结果',
    taskStroopInstr: '点击文字显示的颜色',
    taskStepInstr: '拿着手机走动',
    tasksRemaining: '个任务剩余',
    // Shake Alarm
    shakeAlarm: '抖蓝闹钟',
    shakeTotalTime: '总时长',
    shakePoints: '抖蓝时间点',
    addShakePoint: '添加时间点',
    shakeNow: '抖蓝时间到！',
    shakeFinished: '计时结束！',
    completeShake: '完成抖蓝',
    finish: '结束',
    noShakeAlarms: '暂无抖蓝闹钟',
    shakePoint: '时间点',
    running: '进行中'
  }
};

@Injectable({
  providedIn: 'root'
})
export class LocalizationService {
  currentLang = signal<Lang>('zh');

  toggleLang() {
    this.currentLang.update(l => l === 'en' ? 'zh' : 'en');
  }

  t = computed(() => DICTIONARY[this.currentLang()]);
}